### ISSUE TITLE
Helm Repo web site certificate has expired(self-signed certificate)

### ISSUE THREAD

**Issue by mritd** [traefik/traefik-helm-chart#527] opened 2021-11-18 10:07 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10

### What version of Traefik are you using?

2.5.4

### What did you do?

helm install traefik traefik/traefik

**Helm Repo(https://helm.traefik.io/traefik/index.yaml ) web site certificate has expired**

### What did you see instead?

Helm Repo web site certificate has expired

### What is your environment & configuration?

Helm Repo web site certificate has expired

**Comment by rafaribe** [comment] 2021-11-18 10:07
Same problem here

**Comment by mritd** [comment] 2021-11-18 10:09
The site certificate is replaced by a self-signed certificate 😭😭😭😭😭😭

**Comment by Links2004** [comment] 2021-11-18 10:09
can confirm:

```
openssl s_client -connect helm.traefik.io:443
CONNECTED(00000003)
depth=0 CN = TRAEFIK DEFAULT CERT
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = TRAEFIK DEFAULT CERT
verify return:1
---
Certificate chain
 0 s:CN = TRAEFIK DEFAULT CERT
   i:CN = TRAEFIK DEFAULT CERT
---
```

**Comment by greenbourne277** [comment] 2021-11-18 10:11
I just was about to post this. Thanks. Here the output of the helm binary:


```
STDERR:
  Error: looks like "https://helm.traefik.io/traefik" is not a valid chart repository or cannot be reached: Get "https://helm.traefik.io/traefik/index.yaml": x509: certificate is valid for 1c2f9c3ef780121923d06e6ba2f98f03.9f7f00942d5a07efc825f015d8886829.traefik.default, not helm.traefik.io

```

**Comment by rafaribe** [comment] 2021-11-18 10:12
> The site certificate is replaced by a self-signed certificate 😭😭😭😭😭😭

Update clearly they need to integrate with cert manager 😂😂😂

**Comment by mritd** [comment] 2021-11-18 10:14
> > The site certificate is replaced by a self-signed certificate 😭😭😭😭😭😭
> 
> Clearly they need to integrate with cert manager 😂😂😂

Do you want to say "Caddy YES!"?  XDDD

**Comment by ldez** [comment] 2021-11-18 10:15
Hello, we are on it, it will be fixed quickly

**Comment by ldez** [comment] 2021-11-18 10:19
The problem is fixed.

**Closed by ldez** 2021-11-18 10:19 UTC
Labels: kind/bug/confirmed
