### ISSUE TITLE
Helm chart not applying serverstransports.traefik.containo.us

### ISSUE THREAD

**Issue by mnorrsken** [traefik/traefik-helm-chart#343] opened 2021-01-24 01:18 UTC
Helm chart is not applying serverstransports.traefik.containo.us when upgrading from 2.3 to 2.4
`helm upgrade --repo https://helm.traefik.io/traefik -i --atomic -n kube-system -f values.yml traefik traefik`

Log excerpt:
```
E0124 01:04:16.800386       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1alpha1.ServersTransport: failed to list *v1alpha1.ServersTransport: the server could not find the requested resource (get serverstransports.traefik.containo.us)
```

**Comment by mnorrsken** [comment] 2021-01-24 01:26
Fix:
```
# kubectl apply -f -
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serverstransports.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: ServersTransport
    plural: serverstransports
    singular: serverstransport
  scope: Namespaced
```
<ctrl-d>

**Comment by mnorrsken** [comment] 2021-01-24 01:35
This is a helm restriction, CRDS are not supported with upgrade command. Could this possibly be indicated in the output from helm upgrade?

**Comment by SantoDE** [comment] 2021-02-03 15:08
Duplicate of #349.

Closed :)

**Closed by SantoDE** 2021-02-03 15:08 UTC
Labels: kind/enhancement
