### ISSUE TITLE
Helm install getting error

### ISSUE THREAD

**Issue by shrisathesh** [traefik/traefik-helm-chart#331] opened 2020-12-31 05:15 UTC
Getting error while installing "helm install traefik traefik/traefik" and aswell installing crds

Error: failed to install CRD crds/ingressroute.yaml: CustomResourceDefinition.apiextensions.k8s.io "ingressroutes.traefik.containo.us" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as storage version, status.storedVersions: Invalid value: []string(nil): must have at least one stored version]

**Comment by anthr76** [comment] 2020-12-31 05:30
Facing this issue as well

**Comment by SantoDE** [comment] 2020-12-31 10:21
Duplicate of #329

**Closed** 2020-12-31 10:22 UTC
