### ISSUE TITLE
CRD apiextensions.k8s.io/v1beta1 is deprecated

### ISSUE THREAD

**Issue by obeyler** [traefik/traefik-helm-chart#369] opened 2021-02-23 17:15 UTC
```
apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+;
use apiextensions.k8s.io/v1 CustomResourceDefinition
```
Do you plan to migrate to apiextensions.k8s.io/v1 ?

**Comment by ldez** [comment] 2021-02-23 17:17
Duplicate of #5473

**Closed by ldez** 2021-02-23 17:17 UTC
