### ISSUE TITLE
latest label changes break upgrades

### ISSUE THREAD

**Issue by pfragoso** [traefik/traefik-helm-chart#714] opened 2022-11-10 11:05 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

15.1.1

### What version of Traefik are you using?

2.9.1

### What did you do?

I've tried to upgrade from the chart version from 15.1.1 to 20.1.0

### What did you see instead?

When doing the upgrade it fails due to a change in the labels.

Error: cannot patch "traefik-" with kind Deployment: Deployment.apps "traefik" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"traefik-kube-system", "app.kubernetes.io/name":"traefik"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

### What is your environment & configuration?

EKS with default values files.

### Additional Information

```shell
This seems related to the changes regarding labels. https://github.com/traefik/traefik-helm-chart/commit/2dfe76fcfad014e1a8e4197b90c5c518eff30e92

With adding the -{{ .Release.Namespace }} to the matching breaks upgrades as is immutable field. Any reason for this?

Some useful information https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#names-and-labels
```

**Comment by charlie-haley** [comment] 2022-11-10 13:22
Hi @pfragoso, this is a duplicate of https://github.com/traefik/traefik-helm-chart/issues/685. You will need to recreate your `Deployment` as we made some changes to the label selectors in version 17.0.0.0

**Closed by charlie-haley** 2022-11-10 13:22 UTC
Labels: status/0-needs-triage

**Comment by pfragoso** [comment] 2022-11-10 14:24
Hi @charlie-haley.

Thanks for the quick reply. I understand that breaking changes are also part of releasing software and I know how to fix it.
It's just in some scenarios to remove a deployment for an ingress controller can lead to outages.

My only concern it's the decision for the breaking change, or in this case why we need the Release Namespace in the new labels?

**Comment by charlie-haley** [comment] 2022-11-10 14:39
There were some use-cases where people were installing multiple instances of the chart with the same release name, so we had to make some changes to ensure that the labels weren't clashing across instances.

We try avoid making changes like this if possible, but sometimes it's unavoidable.

**Comment by pfragoso** [comment] 2022-11-10 18:01
Is this a limited use case?

I think it would be just easier to keep the default and add an object just like the fullnameOverride or create a new one ie AllowSameReleaseName now that the label definition is in the _helper.tpl.

Just feel that breaking change for a specific use case like this can easily be added as an option without breaking users that use this helm chart in production.

**Comment by takirala** [comment] 2022-11-17 02:20
i hit this today too :( 

having a CI to validate upgradability would be nice.
