### ISSUE TITLE
Peristence permission problems 660, should be 600

### ISSUE THREAD

**Issue by zzvara** [traefik/traefik-helm-chart#257] opened 2020-09-03 16:35 UTC
Deployed as:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik-default
  namespace: kube-system
spec:
  chart:
    repository: https://containous.github.io/traefik-helm-chart
    name: traefik
    version: 9.1.0
  releaseName: traefik-default
  values:
    ingressRoute:
      dashboard:
        enabled: false
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 100Mi
      storageClass: "ceph-replicated"
      path: /data
      annotations: {}
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
    additionalArguments:
      - "--serverstransport.maxidleconnsperhost=10"
      - "--certificatesresolvers.dns-cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.dns-cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.dns-cloudflare.acme.dnschallenge.delaybeforecheck=60"
      - "--certificatesresolvers.dns-cloudflare.acme.email=redacted"
      - "--certificatesresolvers.dns-cloudflare.acme.storage=/data/dns-cloudflare.json"
      - "--certificatesresolvers.tls.acme.tlschallenge=true"
      - "--certificatesresolvers.tls.acme.email=redacted"
      - "--certificatesresolvers.tls.acme.storage=/data/tls.json"
      - "--providers.kubernetescrd.throttleduration=15"
    ports:
      traefik:
        expose: true
      web:
        port: 30080
        nodePort: 30080
      websecure:
        port: 30443
        nodePort: 30443
    service:
      type: NodePort
    resources:
      requests:
        cpu: "500m"
        memory: "100Mi"
      limits:
        cpu: "1000m"
        memory: "250Mi"
```

When the Pod restarts, certificate resolvers like `tls` and `dns-cloudflare` refuse to work. Logs indicate that files under /data are with permission 660, but Traefik/ACME library requires 600. The Pod works when it starts the first time, every time, then it fails in every consecutive restart.

**Comment by notsureifkevin** [comment] 2020-09-03 19:25
This can be fixed by enabling an `initContainer` which reconciles the permissions in your `/data` directory. See https://github.com/containous/traefik-helm-chart/blob/master/traefik/values.yaml#L21-L29

**Comment by DanielHabenicht** [comment] 2020-10-11 21:42
If you dont want to solve this via `initContainer` you can also use: 
`- --certificatesresolvers.default.acme.storage=tmp/acme.json` - was working for me.

**Comment by zzvara** [comment] 2020-10-12 05:37
I tired to fix it with the initContainer, but it was not working (same problem) and now switched off persistence.

**Comment by SantoDE** [comment] 2020-10-12 08:31
Then that's probably an issue with your underlaying storage provider reconciling the permissions. Can you check if the initContainer did run and what was the result? Like did the chmod change?

**Comment by lexfrei** [comment] 2020-11-23 21:08
The correct link for @notsureifkevin advice is https://github.com/traefik/traefik-helm-chart/blob/f147e4c9d6e5c6bbbe0d8cd64638c29a28b2e99d/traefik/values.yaml#L36-L44

I'm facing this issue too with [longhorn](https://github.com/longhorn/longhorn) storage. This hotfix works great for me, thx!

**Comment by andrei-dascalu** [comment] 2021-01-29 08:20
I wonder why this happens though. The file is generated on the first challenge resolution so if the permissions are expected to be 600, who/what sets them to 660 ?

**Comment by jakubhajek** [comment] 2021-03-30 07:28
hello @andrei-dascalu 

The suggested solution is to set the valid permissions to `/data/acme.json` file prior to Traefik instance is being launched.  The reconciliation of the permission is done manually by the operator by enabling  `initContainers` section.  It is not intentionally enabled by default (e.g.in the pod_template) because the operator should be aware of the behaviour of the filesystem. 

The root cause related to the underlaying storage provider as @SantoDE mentioned in the previous comment.

Please also see similar realted to issues [#6825](https://github.com/traefik/traefik/issues/6825#issuecomment-631450807), [#68920](https://github.com/traefik/traefik/issues/6972), [#399](https://github.com/traefik/traefik-helm-chart/pull/399), #396

**Closed** 2021-03-30 15:13 UTC
Labels: kind/question

**Comment by joelgriffiths** [comment] 2023-02-16 16:51
> hello @andrei-dascalu
> 
> The suggested solution is to set the valid permissions to `/data/acme.json` file prior to Traefik instance is being launched. The reconciliation of the permission is done manually by the operator by enabling `initContainers` section. It is not intentionally enabled by default (e.g.in the pod_template) because the operator should be aware of the behaviour of the filesystem.
> 
> The root cause related to the underlaying storage provider as @SantoDE mentioned in the previous comment.
> 
> Please also see similar realted to issues [#6825](https://github.com/traefik/traefik/issues/6825#issuecomment-631450807), [#6972](https://github.com/traefik/traefik/issues/6972), [#399](https://github.com/traefik/traefik-helm-chart/pull/399), #396

Unfortunately, this is not the easiest problem to crack since it is essentially hidden at the start of the traefik log. It just doesn't assign certs and there is no obvious reason why. This error should cause the system to crash at the very least. Silent failures are a bear to troubleshoot.

**Comment by mloiseleur** [comment] 2023-02-17 09:57
@joelgriffiths Does this work for you by unsetting `fsGroup` on PodSecurityContext ?

```bash
--set podSecurityContext.fsGroup=null
```
