### ISSUE TITLE
defaultCertificate not works on version 10.26.0

### ISSUE THREAD

**Issue by daylioti** [traefik/traefik-helm-chart#635] opened 2022-09-28 12:15 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.26.0

### What version of Traefik are you using?

2.8.7

### What did you do?

Just run "skaffold run" 
deployment didn't had holding on version, so it used latest one (10.26.0)

After changing version to version: 10.25.1 - it works fine

### What did you see instead?

Ingress routes have default traefik certificate instead of generated.
As a result - wrong cert in browser

### What is your environment & configuration?

Local env, minikube with skaffold. Certs generated by mkcert

### Additional Information

```shell
Configuration of default cert for traefik, maybe this would be helpful

apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: kube-system

spec:
  defaultCertificate:
    secretName: traefik-tls
```

**Comment by ldez** [comment] 2022-09-28 12:27
duplicate of #634

**Closed by ldez** 2022-09-28 12:27 UTC
Labels: status/0-needs-triage
