### ISSUE TITLE
Traefik 2.4.0 is not picking up routes from kubernetesCRD

### ISSUE THREAD

**Issue by wargamez** [traefik/traefik-helm-chart#345] opened 2021-01-26 09:20 UTC
I have deployed Traefik on Rancher2 using your helm chart, and since >= 2.4.0-rc1 it is not picking up ingressroutes through kubernetesCRD. If I use the same helm chart (Which is based on your helm chart with a couple of additions for prometheus metrics etc) with the 2.3.7 image tag it works. Any pointers as to what broke in >= 2.4.0-rc1 is appreciated. I see nothing wrong in the logs, the dashboards still says KubernetesCRD is on, but no routes are picked up... The cluster is running Kubernetes Version: v1.19.6

Thanks, 
/E

**Comment by terrych0u** [comment] 2021-01-29 09:14
I got the same issue, upgrade to v2.4.0 then my IngressRoute will disappear on the traefik dashboard, but kubectl command still can get the crd, and all my requests become 404.

Not sure is charts or traefik itself issue

**Comment by ananace** [comment] 2021-01-30 10:25
Updated to 2.4.0 here and Traefik wouldn't discover any of the CRD resources I have either, loosing me both the IngressRoutes as well as all my Middlewares. None of them were discovered in the dashboard. (When I switched it to insecure mode so I could access it)

Downgrading to 2.3.7 let Traefik discover the routes and middlewares again, returning functionality.

**Comment by SantoDE** [comment] 2021-02-03 15:08
Duplicate of #349

**Closed by SantoDE** 2021-02-03 15:08 UTC
Labels: kind/question
