### ISSUE TITLE
Error during installation of traefik through heml-chart

### ISSUE THREAD

**Issue by AllardKrings** [traefik/traefik-helm-chart#745] opened 2022-11-26 08:31 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

20.5.2

### What version of Traefik are you using?

2.0

### What did you do?

1) installed microk8s on ubuntu 22.04
2) added helm repo 
3) installed traefik

### What did you see instead?

Error: INSTALLATION FAILED: template: traefik/templates/_podtemplate.tpl:206:17: executing "traefik.podTemplate" at <eq .Values.metrics.prometheus.addEntryPointsLabels false>: error calling eq: incompatible types for comparison

### What is your environment & configuration?

Rappberry pi
Ubuntu 22.04
Microk8s

**Comment by ldez** [comment] 2022-11-26 09:13
Duplicate of #741

**Closed by ldez** 2022-11-26 09:13 UTC
Labels: status/0-needs-triage
