### ISSUE TITLE
helm.traefik.io is down

### ISSUE THREAD

**Issue by joseEnrique** [traefik/traefik-helm-chart#565] opened 2022-02-23 10:06 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

The place where the chart is down
`curl  -vvI https://helm.traefik.io/traefik/index.yaml
*   Trying 18.158.201.124:443...
* Connected to helm.traefik.io (18.158.201.124) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=helm.traefik.io
*  start date: Jan 27 14:02:05 2022 GMT
*  expire date: Apr 27 14:02:04 2022 GMT
*  subjectAltName: host "helm.traefik.io" matched cert's "helm.traefik.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f8a4d00f800)
> HEAD /traefik/index.yaml HTTP/2
> Host: helm.traefik.io
> user-agent: curl/7.77.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 404
**HTTP/2 404**`

**Comment by ldez** [comment] 2022-02-23 10:10
Hello,

thank you for your report, we are on it, stay tuned.

**Comment by ldez** [comment] 2022-02-23 10:19
The problem is fixed now :gift:

**Closed by ldez** 2022-02-23 10:19 UTC
Labels: kind/bug/confirmed
